<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" attributeFormDefault="unqualified" elementFormDefault="qualified">

	<xs:element name="repairs" type="ServiceMessageRootType"/>

	<xs:complexType name="ServiceMessageRootType">
		<xs:sequence>
			<xs:element maxOccurs="unbounded" minOccurs="0" name="repair" type="ServiceMessageType"/>
		</xs:sequence>
	</xs:complexType>

	<xs:complexType name="ServiceMessageType">
		<xs:sequence>
			<xs:element maxOccurs="unbounded" minOccurs="0" name="x2" type="X2MessageType"/>
		</xs:sequence>
		<xs:attribute name="alt_part_no">
			<xs:simpleType>
				<xs:restriction base="xs:string">
				</xs:restriction>
			</xs:simpleType>
		</xs:attribute>
		<xs:attribute name="analysis">
			<xs:simpleType>
				<xs:restriction base="xs:string">
					<xs:minLength value="0"/>
					<xs:maxLength value="100"/>
				</xs:restriction>
			</xs:simpleType>
		</xs:attribute>
		<xs:attribute name="basic_finish_date">
			<xs:simpleType>
				<xs:restriction base="xs:string">
				</xs:restriction>
			</xs:simpleType>
		</xs:attribute>
		<xs:attribute name="basic_start_date">
			<xs:simpleType>
				<xs:restriction base="xs:string">
				</xs:restriction>
			</xs:simpleType>
		</xs:attribute>
		<xs:attribute name="cust_error_note">
			<xs:simpleType>
				<xs:restriction base="xs:string">
					<xs:minLength value="0"/>
					<xs:maxLength value="4000"/>
				</xs:restriction>
			</xs:simpleType>
		</xs:attribute>
		<xs:attribute name="defect_code" use="required">
			<xs:simpleType>
				<xs:restriction base="xs:string">
					<xs:minLength value="0"/>
					<xs:maxLength value="50"/>
				</xs:restriction>
			</xs:simpleType>
		</xs:attribute>
		<xs:attribute name="delivery_note_no">
			<xs:simpleType>
				<xs:restriction base="xs:string">
					<xs:minLength value="0"/>
					<xs:maxLength value="50"/>
				</xs:restriction>
			</xs:simpleType>
		</xs:attribute>
		<xs:attribute name="designator">
			<xs:simpleType>
				<xs:restriction base="xs:string">
					<xs:minLength value="0"/>
					<xs:maxLength value="50"/>
				</xs:restriction>
			</xs:simpleType>
		</xs:attribute>
		<xs:attribute name="epidemic" use="required">
			<xs:simpleType>
				<xs:restriction base="xs:boolean">
				</xs:restriction>
			</xs:simpleType>
		</xs:attribute>
		<xs:attribute name="error_code" use="required">
			<xs:simpleType>
				<xs:restriction base="xs:string">
					<xs:minLength value="0"/>
					<xs:maxLength value="50"/>
				</xs:restriction>
			</xs:simpleType>
		</xs:attribute>
		<xs:attribute name="defect_code_group">
			<xs:simpleType>
				<xs:restriction base="xs:string">
				</xs:restriction>
			</xs:simpleType>
		</xs:attribute>
		<xs:attribute name="error_group">
			<xs:simpleType>
				<xs:restriction base="xs:string">
				</xs:restriction>
			</xs:simpleType>
		</xs:attribute>
		<xs:attribute name="error_text">
			<xs:simpleType>
				<xs:restriction base="xs:string">
				</xs:restriction>
			</xs:simpleType>
		</xs:attribute>
		<xs:attribute name="failure_origin_code">
			<xs:simpleType>
				<xs:restriction base="xs:string">
					<xs:minLength value="0"/>
					<xs:maxLength value="100"/>
				</xs:restriction>
			</xs:simpleType>
		</xs:attribute>
		<xs:attribute name="part_no" use="required">
			<xs:simpleType>
				<xs:restriction base="xs:string">
					<xs:minLength value="1"/>
					<xs:maxLength value="20"/>
				</xs:restriction>
			</xs:simpleType>
		</xs:attribute>
		<xs:attribute name="plant" use="required">
			<xs:simpleType>
				<xs:restriction base="xs:string">
					<xs:minLength value="1"/>
					<xs:maxLength value="50"/>
				</xs:restriction>
			</xs:simpleType>
		</xs:attribute>
		<xs:attribute name="report_ext">
			<xs:simpleType>
				<xs:restriction base="xs:string">
					<xs:minLength value="0"/>
					<xs:maxLength value="4000"/>
				</xs:restriction>
			</xs:simpleType>
		</xs:attribute>
		<xs:attribute name="report_int">
			<xs:simpleType>
				<xs:restriction base="xs:string">
					<xs:minLength value="0"/>
					<xs:maxLength value="4000"/>
				</xs:restriction>
			</xs:simpleType>
		</xs:attribute>
		<xs:attribute name="revision" use="required">
			<xs:simpleType>
				<xs:restriction base="xs:string">
					<xs:minLength value="0"/>
					<xs:maxLength value="50"/>
				</xs:restriction>
			</xs:simpleType>
		</xs:attribute>
		<xs:attribute name="rma" use="required">
			<xs:simpleType>
				<xs:restriction base="xs:string">
					<xs:minLength value="1"/>
					<xs:maxLength value="50"/>
				</xs:restriction>
			</xs:simpleType>
		</xs:attribute>
		<xs:attribute name="rma_arrival_date">
			<xs:simpleType>
				<xs:restriction base="xs:string">
				</xs:restriction>
			</xs:simpleType>
		</xs:attribute>
		<xs:attribute name="rma_shipment_date">
			<xs:simpleType>
				<xs:restriction base="xs:string">
				</xs:restriction>
			</xs:simpleType>
		</xs:attribute>
		<xs:attribute name="rma_type_id" use="required">
			<xs:simpleType>
				<xs:restriction base="xs:string">
					<xs:minLength value="0"/>
					<xs:maxLength value="50"/>
				</xs:restriction>
			</xs:simpleType>
		</xs:attribute>
		<xs:attribute name="rma_type_group">
			<xs:simpleType>
				<xs:restriction base="xs:string">
				</xs:restriction>
			</xs:simpleType>
		</xs:attribute>
		<xs:attribute name="serial_no" use="required">
			<xs:simpleType>
				<xs:restriction base="xs:string">
					<xs:minLength value="0"/>
					<xs:maxLength value="50"/>
				</xs:restriction>
			</xs:simpleType>
		</xs:attribute>
		<xs:attribute name="service_notif_no">
			<xs:simpleType>
				<xs:restriction base="xs:string">
					<xs:minLength value="0"/>
					<xs:maxLength value="50"/>
				</xs:restriction>
			</xs:simpleType>
		</xs:attribute>
		<xs:attribute name="service_order" use="required">
			<xs:simpleType>
				<xs:restriction base="xs:long">
				</xs:restriction>
			</xs:simpleType>
		</xs:attribute>
		<xs:attribute name="state" use="required">
			<xs:simpleType>
				<xs:restriction base="xs:string">
					<xs:minLength value="1"/>
					<xs:maxLength value="50"/>
				</xs:restriction>
			</xs:simpleType>
		</xs:attribute>
		<xs:attribute name="task_id" use="required">
			<xs:simpleType>
				<xs:restriction base="xs:string">
					<xs:minLength value="0"/>
					<xs:maxLength value="50"/>
				</xs:restriction>
			</xs:simpleType>
		</xs:attribute>
		<xs:attribute name="task_group">
			<xs:simpleType>
				<xs:restriction base="xs:string">
				</xs:restriction>
			</xs:simpleType>
		</xs:attribute>
		<xs:attribute name="task_text">
			<xs:simpleType>
				<xs:restriction base="xs:string">
				</xs:restriction>
			</xs:simpleType>
		</xs:attribute>
		<xs:attribute name="work_center">
			<xs:simpleType>
				<xs:restriction base="xs:string">
				</xs:restriction>
			</xs:simpleType>
		</xs:attribute>
		<xs:attribute name="position">
			<xs:simpleType>
				<xs:restriction base="xs:string">
					<xs:minLength value="0"/>
					<xs:maxLength value="100"/>
				</xs:restriction>
			</xs:simpleType>
		</xs:attribute>
		<xs:anyAttribute/>
	</xs:complexType>

	<xs:complexType name="X2MessageType">
		<xs:sequence>
		</xs:sequence>
		<xs:attribute name="x2_alt_part_no">
			<xs:simpleType>
				<xs:restriction base="xs:string">
				</xs:restriction>
			</xs:simpleType>
		</xs:attribute>
		<xs:attribute name="x2_analysis">
			<xs:simpleType>
				<xs:restriction base="xs:string">
					<xs:minLength value="0"/>
					<xs:maxLength value="100"/>
				</xs:restriction>
			</xs:simpleType>
		</xs:attribute>
		<xs:attribute name="x2_cust_error_note">
			<xs:simpleType>
				<xs:restriction base="xs:string">
					<xs:minLength value="0"/>
					<xs:maxLength value="4000"/>
				</xs:restriction>
			</xs:simpleType>
		</xs:attribute>
		<xs:attribute name="x2_defect_code" use="required">
			<xs:simpleType>
				<xs:restriction base="xs:string">
					<xs:minLength value="0"/>
					<xs:maxLength value="50"/>
				</xs:restriction>
			</xs:simpleType>
		</xs:attribute>
		<xs:attribute name="x2_defect_code_group">
			<xs:simpleType>
				<xs:restriction base="xs:string">
				</xs:restriction>
			</xs:simpleType>
		</xs:attribute>
		<xs:attribute name="x2_designator">
			<xs:simpleType>
				<xs:restriction base="xs:string">
					<xs:minLength value="0"/>
					<xs:maxLength value="50"/>
				</xs:restriction>
			</xs:simpleType>
		</xs:attribute>
		<xs:attribute name="x2_error_code" use="required">
			<xs:simpleType>
				<xs:restriction base="xs:string">
					<xs:minLength value="0"/>
					<xs:maxLength value="50"/>
				</xs:restriction>
			</xs:simpleType>
		</xs:attribute>
		<xs:attribute name="x2_error_code_group">
			<xs:simpleType>
				<xs:restriction base="xs:string">
				</xs:restriction>
			</xs:simpleType>
		</xs:attribute>
		<xs:attribute name="x2_error_text">
			<xs:simpleType>
				<xs:restriction base="xs:string">
				</xs:restriction>
			</xs:simpleType>
		</xs:attribute>
		<xs:attribute name="x2_id" use="required">
			<xs:simpleType>
				<xs:restriction base="xs:long">
				</xs:restriction>
			</xs:simpleType>
		</xs:attribute>
		<xs:attribute name="x2_part_no" use="required">
			<xs:simpleType>
				<xs:restriction base="xs:string">
					<xs:minLength value="1"/>
					<xs:maxLength value="20"/>
				</xs:restriction>
			</xs:simpleType>
		</xs:attribute>
		<xs:attribute name="x2_position">
			<xs:simpleType>
				<xs:restriction base="xs:string">
					<xs:minLength value="0"/>
					<xs:maxLength value="100"/>
				</xs:restriction>
			</xs:simpleType>
		</xs:attribute>
		<xs:attribute name="x2_revision" use="required">
			<xs:simpleType>
				<xs:restriction base="xs:string">
					<xs:minLength value="0"/>
					<xs:maxLength value="50"/>
				</xs:restriction>
			</xs:simpleType>
		</xs:attribute>
		<xs:attribute name="x2_serial_no" use="required">
			<xs:simpleType>
				<xs:restriction base="xs:string">
					<xs:minLength value="0"/>
					<xs:maxLength value="50"/>
				</xs:restriction>
			</xs:simpleType>
		</xs:attribute>
		<xs:attribute name="x2_state" use="required">
			<xs:simpleType>
				<xs:restriction base="xs:string">
					<xs:minLength value="1"/>
					<xs:maxLength value="50"/>
				</xs:restriction>
			</xs:simpleType>
		</xs:attribute>
		<xs:attribute name="x2_work_center">
			<xs:simpleType>
				<xs:restriction base="xs:string">
				</xs:restriction>
			</xs:simpleType>
		</xs:attribute>
		<xs:anyAttribute/>
	</xs:complexType>
</xs:schema>
